### ISSUE TITLE
Does not work with well with helm

### ISSUE THREAD

**Issue by azzamsa** [gonewest818/dimmer.el#15]
Dimmer dim the helm pop-up. and does not dim other window when switching between them.

```
GNU Emacs 25.1.1 (x86_64-pc-linux-gnu, GTK+ Version 3.22.11) of 2017-09-15, modified by Debian
Helm 20180224.337
```

**Comment by gonewest818** [comment]
I'll need to get some time to look at this, because I keep thinking the `dimmer-exclusion-regexp` should cover this but perhaps it does not. So how would you like it to work? Is it
 -  buffers like "*helm ag*" are not dimmed
 -  and the buffer where you invoked the helm command also stays "bright"?

**Comment by azzamsa** [comment]
Now it dim the right buffer. The active buffer not bright as yours, even I set `dimmer-fraction` to 0.83

```
(use-package dimmmer
  :ensure nil
  :config
  (setq dimmer-fraction 0.83)
  (dimmer-mode t))
```

This is the figure. dimmer.el dim my helm pop-up, and dim-and-bright  when helm updates the content.


![anim](https://user-images.githubusercontent.com/17734314/36637041-945b9396-1a05-11e8-982a-e43dc8b918eb.gif)

**Comment by gonewest818** [comment]
What theme are you using?

**Comment by azzamsa** [comment]
I use [zenburn-theme](http://github.com/bbatsov/zenburn-emacs), version 20180222.1757.

**Comment by gonewest818** [comment]
Ok, first of all I'm noticing the package name "dimmer" is spelled incorrectly in your `use-package` statement (including in your screen capture it says "dimmmer" with 3 m's.).  Secondly, setting `dimmer-fraction` to 0.83 should make the text nearly invisible. That's really high.

I'm not saying this is the reason dimmer isn't dealing with "helm" properly, but there's something else funny about your configuration. Can you fix the spelling in `use-package` and also set `:ensure t` and  `(setq dimmer-fraction 0.50)`, remove the dimmer package in `~/.emacs.d/elpa/`, and restart emacs to reinstall the latest dimmer release? That should look a little more sane.

And then we can go back to the helm thing.

**Comment by azzamsa** [comment]
> Ok, first of all I'm noticing the package name "dimmer" is spelled incorrectly in your use-package 

Oh, really sorry. I don't notice it. Sorry.

>Can you fix the spelling in use-package and also set :ensure t and (setq dimmer-fraction 0.50), remove the dimmer package in ~/.emacs.d/elpa/, and restart emacs to reinstall the latest dimmer release? That should look a little more sane.

Done.

- dimming between buffer works great.
- it still dim helm and mini-buffer even they are active.

![anim](https://user-images.githubusercontent.com/17734314/36703312-aab7d922-1b8d-11e8-95dd-347c034a5ab7.gif)

**Comment by gonewest818** [comment]
Try adding `(setq dimmer-exclusion-regexp "^\*helm.*")` 

That should prevent any of the helm buffers from being dimmed, for example if you switch to buffer `C-x b` the helm list of buffers should be highlighted.  Unfortunately whatever buffer was active when you typed `C-x b` will still be dimmed. I'm not sure what your preference is, but give this a try and let me know.

<img width="1091" alt="screen shot 2018-02-26 at 4 29 45 pm" src="https://user-images.githubusercontent.com/2460918/36703819-5232f8b6-1b12-11e8-8ace-98226083df31.png">

**Comment by gonewest818** [comment]
To prevent dimming the helm buffers *and* the minibuffer, the regex is this:

    (setq dimmer-exclusion-regexp "^\*helm.*\\|^ \*Minibuf-.*")

To make this change I needed to disable and re-enable dimmer, or you can change your config and restart Emacs.

    (dimmer-mode 0)
    (setq dimmer-exclusion-regexp "^\*helm.*\\|^ \*Minibuf-.*")
    (dimmer-mode 1)

**Comment by azzamsa** [comment]
> To prevent dimming the helm buffers and the minibuffer, the regex is this:

I put this in my config, am I missing something ?

```
(use-package dimmer
  :ensure t
  :config
  (setq dimmer-fraction 0.50)
  (setq dimmer-exclusion-regexp "^\*helm.*\\|^ \*Minibuf-.*")
  (dimmer-mode t))
```

- Helm pop-op works great, it does not get dimmed.
- But, something strage, after restarting emacs, I get mini-buffer not dimmed, but after sometimes of invoking helm, the minibuffer also get dimmed.


![anim](https://user-images.githubusercontent.com/17734314/36705998-754903b2-1b9a-11e8-96de-4c392b4683b4.gif)

**Comment by azzamsa** [comment]
I will try to use this setting and report the updates here.

**Comment by gonewest818** [comment]
One adjustment you could make is to exclude the ["echo area"](https://www.gnu.org/software/emacs/manual/html_node/elisp/The-Echo-Area.html) as well as the minibuffer like so:

      (setq dimmer-exclusion-regexp "^\*helm.*\\|^ \*Minibuf-.*\\|^ \*Echo.*")

**Comment by azzamsa** [comment]
I don't know what's wrong with my emacs. but using this 

```
 (setq dimmer-exclusion-regexp "^\*helm.*\\|^ \*Minibuf-.*\\|^ \*Echo.*")
```
makes my minibuffer dimmed since emacs started.

**Comment by azzamsa** [comment]
Thanks lot for the help, gonewest818.

Nothing change in my emacs, the minibuffer dimmer since emacs started. 
I think the error was in my `init.el`.

I will disabled this extension for while, and inspect what's wrong with my init.el .

Thanks lot.

**Comment by azzamsa** [comment]
put the `setq` in `:init` also does not solve the problem

```
(use-package dimmer
  :ensure t
  :init
  (setq dimmer-exclusion-regexp "^\*helm.*\\|^ \*Minibuf-.*\\|^ \*Echo.*")
  :config
  (setq dimmer-fraction 0.50)
  (dimmer-mode t))
```

This is the information I can update here. Thanks.

**Comment by gonewest818** [comment]
Hmm. In terms of configuration, it is ok to set `dimmer-exclusion-regexp` in `:config` before enabling `dimmer-mode`, exactly like you did back in [this earlier comment](https://github.com/gonewest818/dimmer.el/issues/15#issuecomment-368717323). I have roughly the same in my config right now and it's working as expected.  

However, I don't normally use helm, so all I'm doing is creating buffers named `*helm xyz*` by hand to make sure they're not dimmed. I suppose it's possible there is a bad interaction with the actual helm package and I'm not seeing it because I'm not using helm.... When I get some time I can setup helm again and experiment with that.

Or perhaps you could disable helm in your config, restart emacs, and then report back if dimmer handles the minibuffer correctly after that change. I don't want you to stop using helm forever, but I do need a clue what's going on in your case.

**Comment by azzamsa** [comment]
I tried your advice soon as you posted. I think I found the problem.

- Disabling helm doesn't help, the problem still occur. So I try disabling super-save, I think this cause the problem. Because minibuffer dimmed after x minutes (maybe after I switch to other workspace), but disabling super-save still dosn't solve the problem.

- I always run emacs with emacsclient then emacsclient -c (GUI). So I tried emacsclient -t (CLI). **and the problem solved**

**dimmer works fine in emacsclient -t (CLI)**. dimmer does not dim the minibuffer nor helm.
The problem occur only after I switch workspace and come back to emacsclient (GUI).
 When I switch to other workscpase the minibuffer dimmed immediately. *I just notice it*.

Trying to enable super-save and helm in emacsclient -t (CLI), and dimmer still works fine.

I use i3wm.
Any advice for this ?

```
Debian 9
Binary i3 version:  4.13 (2016-11-08, branch "4.13") © 2009 Michael Stapelberg and contributors
Running i3 version: 4.13 (2016-11-08, branch "4.13") (pid 910)
```

**Comment by gonewest818** [comment]
Thanks for helping with that. I think that's the clue I needed. 

Just now I tried `M-x start-server` in an existing Emacs session, then `emacsclient -t foo` from a shell. I got the same problem with the minibuffer. In `ielm` I confirmed `dimmer-exclusion-regexp` wasn't changed, and `(dimmer-filtered-buffer-list)` looks correct too. If I toggle `dimmer-mode` off and on, then I can get the minibuffer to behave again. So it's something to do with the initialization when `emacsclient` opens a new frame.

It doesn't appear to happen when I `M-x make-frame` in an existing Emacs session, only when the frame is created via `emacsclient`.

I'll need some time to debug that but at least I have the repro now.

**Comment by ghost** [comment]
I can reproduce this issue using ivy and company too.

**Comment by azzamsa** [comment]
@nealot This issue happened when you use emacs frame from emacsclient. But it's solved when you don't use emacsclient.

**Comment by ghost** [comment]
Really? I might be experiencing a different issue then because although I'm not using emacsclient I still can't get ivy/minibuffer/echo area to obey the regex.

I'm on i3wm too, if that's relevant.

**Comment by azzamsa** [comment]
Sorry. didn't pay attention to minibuffer correctly.

Yes I can confirm that the regrex way doesn't work.

**Comment by ghost** [comment]
Another odd thing I've noticed is that after changing workspaces or opening other applications in i3, dimmer automatically dims the foreground color. Have you experienced that too?

**Comment by azzamsa** [comment]
I think no.

![anim](https://user-images.githubusercontent.com/17734314/39660499-b4198ae4-506a-11e8-823c-84e10944cb3b.gif)

**Comment by ghost** [comment]
Okay I found out my problem was caused by 
``` (add-hook 'focus-in-hook 'dimmer-config-change-hook)```
```(add-hook 'focus-out-hook 'dimmer-dim-all)```
So all I had to do was remove these hooks and the issue went away.

A suggestion might be to include a customize variable that allows you to set whether or not you want dimmer to work on frames aswell.

**Comment by gonewest818** [comment]
Toggling that behavior with a config setting sounds totally reasonable to me. Do you want to submit a pull request for that?

**Comment by azzamsa** [comment]
@nealot

**Comment by azzamsa** [comment]
@gonewest818 nealot seems to be inactive for long time. Do you consider to add nealot's solution to master ?

**Comment by ghost** [comment]
Sorry, but I stopped using emacs for vscode :cry:

**Comment by azzamsa** [comment]
This issue solved for me. Using following config and step described by @nealot https://github.com/gonewest818/dimmer.el/issues/15#issuecomment-386820673

``` lisp

(use-package dimmer
  :defer 1
  :load-path "~/emacs-packages/dimmer.el/"
  :config
  (setq dimmer-exclusion-predicates '(helm--alive-p window-minibuffer-p))
  (setq dimmer-exclusion-regexp-list
        '("^\\*[h|H]elm.*\\*" "^\\*Minibuf-[0-9]+\\*"
          "^.\\*which-key\\*$" "^*Messages*" "*LV*"))
  (setq dimmer-fraction 0.50)
  (dimmer-mode t))
```

**Comment by gonewest818** [comment]
FYI, this is much better in the most recent commits on the master branch.

**Comment by AnweshGangula** [comment]
> This issue solved for me. Using following config and step described by @nealot [#15 (comment)](https://github.com/gonewest818/dimmer.el/issues/15#issuecomment-386820673)
> 
> ```lisp
> (use-package dimmer
>   :defer 1
>   :load-path "~/emacs-packages/dimmer.el/"
>   :config
>   (setq dimmer-exclusion-predicates '(helm--alive-p window-minibuffer-p))
>   (setq dimmer-exclusion-regexp-list
>         '("^\\*[h|H]elm.*\\*" "^\\*Minibuf-[0-9]+\\*"
>           "^.\\*which-key\\*$" "^*Messages*" "*LV*"))
>   (setq dimmer-fraction 0.50)
>   (dimmer-mode t))
> ```

Looks like this config doesn't work as is anymore.

Note that
- `dimmer-exclusion-regexp-list` has been changed to `dimmer-buffer-exclusion-regexps` AND
- `dimmer-exclusion-predicates` has been changed to `dimmer-prevent-dimming-predicates`

I tried changing these, but still could not get it to work!!
