### ISSUE TITLE
How to exclude Hydra windows and Ivy/Counsel minibuffer interface?

### ISSUE THREAD

**Issue by alienbogart** [gonewest818/dimmer.el#19]
#### Runtime Environment

- MX Linux 17
- GNU Emacs 27.0.50 (build 1, x86_64-pc-linux-gnu, GTK+ Version 3.22.11) of 2018-11-28
- Evil version 1.2.13
- [.emacs.d](https://github.com/mrbig033/dotfiles/tree/master/emacs/emacs_default)
- [packages](https://github.com/mrbig033/dotfiles/blob/master/emacs/emacs_default/packs.el)
- dimmer-20180218.411
- hydra-20181128.1716

I guess I could add my Ivy/Counsel minibuffer and Hydra windows to `dimmer-exclusion-regexp`, but I don't know which terms to use. Hydras and minibuffer don't appear the buffer list. Any idea on how to accomplish that? Thanks!

**Comment by azzamsa** [comment]
@mrbig033 have you find a solution ? I faced the same problem with Hydra

**Comment by azzamsa** [comment]
Solved. Adding `"*LV*"` to `dimmer-exclusion-regexp-list` solved the problem.

Previously:

![2019-01-16-13 03 05](https://user-images.githubusercontent.com/17734314/51229590-84c48480-198f-11e9-9963-f3a734bf8e50.png)

Now:

![2019-01-16-13 03 32](https://user-images.githubusercontent.com/17734314/51229597-88f0a200-198f-11e9-8a41-27ab3960724e.png)

**Comment by stardiviner** [comment]
How about company-box child-frame?

**Comment by azzamsa** [comment]
> How about company-box child-frame?

You mean this?

![Peek 2019-10-24 11-12](https://user-images.githubusercontent.com/17734314/67453005-5e82f200-f64f-11e9-88dc-7e55e2b20deb.gif)

**Comment by alienbogart** [comment]
@azzamsa Thank you for the solve. It's working flawlessly! Could to explain why does it work, though? ;)

In the meantime, not to be a choosing beggar, but may I suggest you share your solutions as text and not images? I had to take a screenshot of your GIF just to make sense of it.

If you don't track your configurations on Git, you can always post it on this field as formatted as code, or use https://gist.github.com/ and similar services if it is too long.

Anyway: I'm happy to be able to use this very useful package once again. Cheers!

**Comment by azzamsa** [comment]
:)

I think I've explained it in my [previous](https://github.com/gonewest818/dimmer.el/issues/19#issuecomment-454663376) comment:

> Solved. Adding "*LV*" to `dimmer-exclusion-regexp-list` solved the problem.

``` elisp
(use-package dimmer
  :defer 1
  :load-path "~/emacs-packages/dimmer.el/"
  :config
  (setq dimmer-exclusion-predicates '(helm--alive-p window-minibuffer-p))
  (setq dimmer-exclusion-regexp-list
        '("^\\*[h|H]elm.*\\*" "^\\*Minibuf-[0-9]+\\*"
          "^.\\*which-key\\*$" "^*Messages*" "*LV*"
          "transient"))
  (setq dimmer-fraction 0.50)
  (dimmer-mode t))
```

Take a note that I use this PR https://github.com/gonewest818/dimmer.el/pull/16, with some addition in. read more in my comment https://github.com/gonewest818/dimmer.el/pull/16#issuecomment-545734769

Btw, this is my .emacs.d repo: https://github.com/azzamsa/emacs.d
