### ISSUE TITLE
dimme background instead of foreground.

### ISSUE THREAD

**Issue by 4goodapp** [gonewest818/dimmer.el#20]
Is it possible to dimme the background (to be darker or lighter) instead of dimming the text/foreground?

There is this package [auto-dim-other-buffers.el](https://github.com/mina86/auto-dim-other-buffers.el) that does that but you have to chose one unique background color instead of a darker/lighter background of the current theme's. So when you change theme, things don't look good. and there is no way to change the dimme level with it.

**Comment by gonewest818** [comment]
I seem to remember looking at this when I first wrote the package, and the challenge was exactly as you describe... what's the best way to mathematically compute a darker (or lighter) background color that is consistent with the rest of theme?  At the time I wasn't able to come up with anything I liked.

**Comment by gonewest818** [comment]
This is a new feature on the master branch, will be picked up in MELPA in the next few hours whenever the next auto-build runs.   Give it a try and see what you think?

**Comment by 4goodapp** [comment]
Will test it once available on MELPA. Thanks.

**Comment by 4goodapp** [comment]
It's working perfectly as expected 👍

I however use `(setq dimmer-fraction 0.08)` instead of `(setq dimmer-fraction 0.3)` with `dimmer-adjustment-mode` set to :background. 

```
(use-package dimmer
  :config
  (setq dimmer-adjustment-mode :background)
  (setq dimmer-exclusion-regexp "^\\*helm.*\\|^ \\*Minibuf-.*")
  (setq dimmer-fraction 0.08)
  (dimmer-mode)
  )

```

**Comment by gonewest818** [comment]
Great! Yes, I agree, the background adjustment feels more aggressive than the foreground.

Note that the Minibuffer is now excluded by default and the `dimmer-exclusion-regexp` variable is now obsolete. In your case you can simplify your `use-package` setup like this:

```
(use-package dimmer
  :config
  (setq dimmer-adjustment-mode :background)
  (setq dimmer-fraction 0.08)
  (dimmer-configure-helm)
  (dimmer-mode t))
```

**Comment by 4goodapp** [comment]
Yes, that, it's more aggressive.
I replaced helm with Ivy/counsel. So I think I can just comment that line.

Now let's suppose I want exclude certain buffer like `*imenu-list*`, How can I set it with `dimmer-exclusion-regexp-list`?

**Comment by gonewest818** [comment]
Try this:
```
(use-package dimmer
  :config
  (setq dimmer-adjustment-mode :background)
  (setq dimmer-fraction 0.08)
  (add-to-list 'dimmer-exclusion-regexp-list "^\\*imenu-list\\*$")
  (dimmer-mode t))
```

**Comment by 4goodapp** [comment]
Perfect!

I think we need a `dimmer-inclusion-regexp-list`so that certain are always dimmed.

**Comment by gonewest818** [comment]
If you can open another ticket for that?  I would always want some way to "un-dim" a buffer by switching to it, but I suppose that’s why we have user preferences.

**Comment by 4goodapp** [comment]
Done #27
