### ISSUE TITLE
Inconsistent behaviour

### ISSUE THREAD

**Issue by manuel-uberti** [gonewest818/dimmer.el#3]
Hi,

first of all thanks for the package, a useful visual aid. I am giving it a try with this snippet in my configuration:
```
(use-package dimmer
  :load-path "~/githubs/dimmer.el"
  :init
  (require 'dimmer)
  (dimmer-activate))
```
The package only seems to work when point is in the minibuffer. Have a look at these screenshots:

![01](https://user-images.githubusercontent.com/8199224/34307009-649c0c0e-e746-11e7-927d-14e6d522531d.png)

![02](https://user-images.githubusercontent.com/8199224/34307031-77080c44-e746-11e7-9ffb-a940c2a3d663.png)

**Comment by gonewest818** [comment]
Hi Manuel,

The way this package is implemented, it depends on buffer-local overrides to the faces in your theme. However, any time you have multiple windows displaying the same buffer they will all dim/undim together.

It’s not possible to distinguish the individual windows, at least not with the face override APIs that I happen to be using. 

I should clarify this in the readme.

So I would first try splitting windows and displaying something else in the second one. It can be the *scratch* buffer or anything else, and confirm that the dimmer at least works for you.

If it still doesn’t work then I’ll ask your emacs version and we can try to narrow down what’s different about your setup.

Thanks for the feedback-

**Comment by manuel-uberti** [comment]
Thanks for the reply. I will be away on holiday for a couple of weeks, but I'll resume testing as soon as I get back.

**Comment by manuel-uberti** [comment]
Hi, I installed the package from MELPA and restarted Emacs. 

This is my configuration:
```
(use-package dimmer
  :ensure t
  :init (dimmer-mode))
```
It still seems to work only when point is in the minibuffer.

I am using GNU Emacs 27.0.50 (build 1, x86_64-debian-linux-gnu, GTK+ Version 3.18.9) of 2018-01-07.

**Comment by manuel-uberti** [comment]
BTW, it only happens as described [here](https://github.com/gonewest818/dimmer.el/pull/5#issuecomment-354369094).
