### ISSUE TITLE
A recent change in Emacs 28 has made the third argument (WHEN) of define-obsolete-function-alias mandatory.

### ISSUE THREAD

**Issue by jeffkowalski** [gonewest818/dimmer.el#50]
Please add ```when``` argument to these calls:

https://github.com/gonewest818/dimmer.el/blob/c5c881cc5c0401467fda2864590558fc612c2943/dimmer.el#L130
https://github.com/gonewest818/dimmer.el/blob/c5c881cc5c0401467fda2864590558fc612c2943/dimmer.el#L601

**Comment by gonewest818** [comment]
Ok, and thanks for reporting this.

**Comment by gonewest818** [comment]
I don't have Emacs 28 compiled at the moment but I am running some basic checks on 25, 26, 27 and 28 in CircleCI.  Pls let me know if this doesn't resolve it for you.
