### ISSUE TITLE
Use with emacs-mini-frame

### ISSUE THREAD

**Issue by mclearc** [gonewest818/dimmer.el#56]
Thanks for your work on this package. I use it with [mini-frame](https://github.com/muffinmad/emacs-mini-frame), which works well except for the fact that I'd like to be able to call the mini-frame without dimming whatever selected window I was previously working in. Is this possible? Here's my current setting (I'm on emacs 28 if that matters):

```emacs-lisp
(use-package dimmer
  :straight (:host github :repo "gonewest818/dimmer.el")
  :hook (after-init . dimmer-mode)
  :config
  (setq mini-frame-create-lazy nil)
  (setq dimmer-exclusion-predicates '(window-minibuffer-p))
  (setq dimmer-fraction 0.5)
  (setq dimmer-adjustment-mode :foreground)
  (setq dimmer-use-colorspace :rgb)
  (setq dimmer-watch-frame-focus-events nil)
  (dimmer-configure-which-key)
  (dimmer-configure-magit)
  (dimmer-configure-posframe))
```

**Comment by gonewest818** [comment]
This usually comes down to implementing a function that can determine if mini-frame is active and then adding that function to `dimmer-prevent-dimming-predicates`.   I don't have mini-frame in my configuration though, so it would be a big of legwork for someone to figure it out.
