### ISSUE TITLE
Buffer is dimmed very briefly after frame is focused (Gnome)

### ISSUE THREAD

**Issue by WhatDothLife** [gonewest818/dimmer.el#57]
I noticed that when I'm changing my focus to an Emacs frame, the current buffer is dimmed for a short time (looks like it's blinking). Is there any chance this can be fixed by using another hook?

**Comment by gonewest818** [comment]
Hard to say what’s happening without debugging a reproducible case. 

However - There is a configuration setting that controls how dimmer responds when emacs loses focus…some people prefer to leave the most recently active window highlighted, and I prefer if dimmer dims everything. Anyway, that’s a choice and if you disable that setting it might help in your case …

Doesn’t explain why the flicker is happening, of course, but would maybe reduce the annoyance.

**Comment by WhatDothLife** [comment]
Indeed, setting `dimmer-watch-frame-focus-events` to `nil` solved the issue. Unfortunately, it took me way too much time to figure out it has to be set before `dimmer-mode` is invoked for the first time. Otherwise, it has no effect for me.

Maybe, the documentation of the variable could be extended. So far, there's only this hint:
> Restart Emacs after changing this configuration.

Thank you for your quick response (again!). I'm a huge fan of dimmer, it's one of my most valuable packages.

**Comment by gonewest818** [comment]
Great, I'm glad the workaround is working out for you.

Appreciate the feedback on the docs, too! I'll make that clearer. 

I'm curious to see a reproducible case -- if anyone out there happens to pinpoint a set of conditions when this happens, it would be good to know. 

Thanks

**Comment by WhatDothLife** [comment]
I think it might actually be a Gnome problem. The Emacs frame briefly loses focus when the navigation window is launched and after it exits. Here is a recording:

![dimmer](https://user-images.githubusercontent.com/33008303/142738721-e6c5ad18-a681-412b-8a40-f22cee23582a.gif)

Of course, it wouldn't be surprising if it was due to a quirk of Emacs, but I don't know how to debug it....

**Comment by gonewest818** [comment]
Yeah, it does look like the switcher is somehow causing that. Thanks for that video.

**Comment by gonewest818** [comment]
I pushed an update to the documentation.

I'm considering the rest of the issue a gnome bug and therefore "not a bug" based on the evidence above.  Let me know if you think I should reconsider that.  thanks-
